apiVersion: v1
kind: Service
metadata:
  name: advanced-search-service
  namespace: commerce
spec:
  selector:
    app: advanced-search-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
